-- 02_file_format_and_table.sql
-- Step 2 and 3: create FILE FORMAT and TABLE
-- File format for CSVs (adjust DELIMITER / SKIP_HEADER etc as needed)

CREATE FILE FORMAT IF NOT EXISTS DEMO_DATABASE.DEMO_SCHEMA.CUSTOMER_CSV_FF
  TYPE = 'CSV'
  COMPRESSION = 'AUTO'
  FIELD_DELIMITER = ','
  RECORD_DELIMITER = '\n'
  SKIP_HEADER = 1
  SKIP_BLANK_LINES = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

-- Create table (example)
CREATE OR REPLACE TABLE DEMO_DATABASE.DEMO_SCHEMA.CUSTOMER_CVS_FF (
  CUST_ID VARCHAR(50),
  CREDIT_CARD_NUMBER VARCHAR(50),
  BALANCE NUMBER(10,2),
  PURCHASES NUMBER(10,2),
  INSTALLMENTS_PURCHASES NUMBER(10,2),
  CASH_ADVANCE NUMBER(10,2),
  CREDIT_LIMIT NUMBER(10,2),
  PAYMENTS NUMBER(10,2),
  MINIMUM_PAYMENTS NUMBER(10,2),
  TENURE NUMBER(10,2),
  DATE_OF_TXN DATE
);
