
--- Using accountadmin
USE ROLE ACCOUNTADMIN;

---Creating Warehouse and Use the Warehouse
CREATE WAREHOUSE IF NOT EXISTS DEMO_WAREHOUSE;
USE WAREHOUSE DEMO_WAREHOUSE;

--- Create database and use the database
CREATE DATABASE IF NOT EXISTS DEMO_DATABASE;
USE DEMO_DATABASE;

--- Create schema and use the Schema
CREATE SCHEMA IF NOT EXISTS DEMO_SCHEMA;
USE SCHEMA DEMO_SCHEMA;

--- Create Stage
CREATE STAGE IF NOT EXISTS DEMO_STAGE;

--- Create file format
CREATE FILE FORMAT IF NOT EXISTS DEMO_DATABASE.DEMO_SCHEMA.CUSTOMER_CSV_FF
TYPE = 'CSV'
COMPRESSION = 'AUTO'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1
SKIP_BLANK_LINES = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

--- Create Table
CREATE OR REPLACE TABLE DEMO_DATABASE.DEMO_SCHEMA.CUSTOMER_CVS_FF (
CUST_ID VARCHAR(50),
CREDIT_CARD_NUMBER VARCHAR(50),
BALANCE NUMBER(10,2),
PURCHASES NUMBER(10,2),
INSTALLMENTS_PURCHASES NUMBER(10,2),
CASH_ADVANCE NUMBER (10,2),
CREDIT_LIMIT NUMBER(10,2),
PAYMENTS NUMBER(10,2),
MINIMUM_PAYMENTS NUMBER(10,2),
TENURE NUMBER(10,2),
DATE_OF_TXN DATE
);

--- Check Duplicate
SELECT CUST_ID,COUNT(*) AS TOTAL_COUNT
FROM DEMO_DATABASE.DEMO_SCHEMA.CUSTOMER_CVS_FF
GROUP BY ALL
HAVING COUNT(*) > 1
ORDER BY 2 DESC;

