-- setup.sql
-- 1. Create role, warehouse, database, schema, stage, and file format

CREATE ROLE IF NOT EXISTS DEMO_ROLE;
-- Granting rights to role is environment specific; assign as needed.

CREATE WAREHOUSE IF NOT EXISTS DEMO_WAREHOUSE;
USE WAREHOUSE DEMO_WAREHOUSE;

CREATE DATABASE IF NOT EXISTS DEMO_DATABASE;
USE DEMO_DATABASE;

CREATE SCHEMA IF NOT EXISTS DEMO_SCHEMA;
USE SCHEMA DEMO_SCHEMA;

-- Internal stage (for small internal uploads; use SnowSQL PUT to upload files to internal stage)
CREATE STAGE IF NOT EXISTS DEMO_STAGE;

-- File format for CSV files
CREATE FILE FORMAT IF NOT EXISTS DEMO_DATABASE.DEMO_SCHEMA.CUSTOMER_CSV_FF
TYPE = 'CSV'
COMPRESSION = 'AUTO'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1
SKIP_BLANK_LINES = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

-- Table (destination)
CREATE OR REPLACE TABLE DEMO_DATABASE.DEMO_SCHEMA.CUSTOMER_CVS_FF (
  CUST_ID VARCHAR(50),
  CREDIT_CARD_NUMBER VARCHAR(50),
  BALANCE NUMBER(10,2),
  PURCHASES NUMBER(10,2),
  INSTALLMENTS_PURCHASES NUMBER(10,2),
  CASH_ADVANCE NUMBER(10,2),
  CREDIT_LIMIT NUMBER(10,2),
  PAYMENTS NUMBER(10,2),
  MINIMUM_PAYMENTS NUMBER(10,2),
  TENURE NUMBER(10,2),
  DATE_OF_TXN DATE,
  SOURCE_FILE VARCHAR(255), -- useful for dedupe and traceability
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
